"""
This module contains the ConfigManager class, which is a singleton class that manages the configuration of the application.
It loads environment variables and sets them as attributes of the ConfigManager instance. It also initializes the logger with the attributes of the ConfigManager instance.
It loads the detection configuration from a file and sets the attributes of the ConfigManager instance.
"""
import os
from lib.common import Logger
from configparser import ConfigParser

class ConfigManager:
    """
    Singleton class that manages the configuration of the application.
    """
    
    _instance = None
    def __new__(cls):
        """
        Creates a new instance of the ConfigManager class if it does not exist.
        """
        if not cls._instance:
            # Initialize the class instance
            cls._instance = super(ConfigManager, cls).__new__(cls)
            
            # Put any initialization here.
            cls.__service_name = None
            cls.__version = None
            cls.__metrics_port = None
            cls.__log_level = None
            cls.__env = None
            cls.__detection_config_file_path = None
            cls.__segmentation_config_file_path = None  # not used
            cls.__logger = None
            # End of initialization section

            # Load configs
            cls._instance._load_environment()
            cls._instance._init_logger()
            cls._instance._load_detection_config()
            # End of loading configs

            cls._instance.__logger.debug("ConfigManager init completed", service_config=cls.__service_config)
        return cls._instance

    def _load_environment(self):
        """
        Loads environment variables and sets them as attributes of the ConfigManager instance.
        """
        self.__service_name = os.getenv("APP_NAME", "livestream-ai-worker")
        self.__version = os.getenv("VERSION", "dev-version")
        self.__metrics_port = os.getenv("METRICS_PORT", 8000)
        self.__log_level = os.getenv("LOG_LEVEL", "info")
        self.__env = os.getenv("ENVIRONMENT", "dev")
        self.__detection_config_file_path = os.getenv("DETECTION_CONFIG_FILE_PATH", "configs/detection_nvinfer.txt")
        self.__segmentation_config_file_path = os.getenv("SEGMENTATION_CONFIG_FILE_PATH", "configs/segmentation_nvinfer.txt")

    def _init_logger(self):
        """
        Initializes the logger with the attributes of the ConfigManager instance.
        """
        self.__logger = Logger(
            log_level=self.get_logger_level(),
            app_name=self.get_app_name(),
            app_version=self.get_app_version(),
            environment=self.get_environment()
        ).get_logger()

    def _load_detection_config(self):
        """
        Loads the detection configuration from a file and sets the attributes of the ConfigManager instance.
        """
        parser = ConfigParser()
        parser.read(self.__detection_config_file_path)

        config_parent_dir = os.path.abspath(os.path.dirname(self.__detection_config_file_path))

        self.__logger.debug("Loaded detection config from file: {}".format(parser.sections()),
                            property=parser["property"], attr=parser["class-attrs-all"])

        # check if parser has the required sections
        if "property" not in parser.sections() or "class-attrs-all" not in parser.sections():
            raise ValueError("Invalid detection config file: {}, check {}".format(parser.sections(),
                                                                                  self.__detection_config_file_path))

        # overriding properties
        gpu_id = os.getenv("GPU_ID", "0")
        parser["property"]["gpu-id"] = gpu_id
        self.__logger.debug("Overriding detection config property: gpu-id", gpu_id=gpu_id)

        self.__logger.debug("Checking onnx file")
        if "onnx-file" not in parser["property"]:
            raise ValueError("onnx-file value not found config file: {}".format(self.__detection_config_file_path))

        # check if onnx file exists
        onnx_file = parser["property"]["onnx-file"]
        if not os.path.exists(os.path.abspath("{}/{}".format(config_parent_dir, onnx_file))):
            raise ValueError("Onnx file not found: {}".format(onnx_file))

        # set engine file path
        engine_file_name = "model_b{}_gpu{}_fp32.engine".format(len(self.__input_rtsp_streams), gpu_id)
        engine_file = "{}/{}".format(os.getcwd(), engine_file_name)
        parser["property"]["model-engine-file"] = engine_file
        self.__logger.debug("Overriding detection config property: model-engine-file",
                            engine_file_name=engine_file_name)
        if not os.path.exists(engine_file):
            self.__logger.warning("Engine file not found: {}! It will be generated by nvinfer".format(engine_file))

        # set batch size
        parser["property"]["batch-size"] = str(len(list(filter(lambda x: x.enabled, self.__input_rtsp_streams))))
        self.__logger.debug("Overriding detection config property: batch-size",
                            batch_size=len(self.__input_rtsp_streams))

        if "nms-iou-threshold" not in parser["class-attrs-all"]:
            parser["class-attrs-all"]["nms-iou-threshold"] = "0.45"

        if "pre-cluster-threshold" not in parser["class-attrs-all"]:
            parser["class-attrs-all"]["pre-cluster-threshold"] = "0.45"

        if "topk" not in parser["class-attrs-all"]:
            parser["class-attrs-all"]["topk"] = "300"

        # write config file
        with open(self.__detection_config_file_path, "w") as f:
            parser.write(f)
        self.__logger.debug("Wrote detection config to file: {}".format(self.__detection_config_file_path))


    def get_logger_level(self):
        """
        Returns the log level attribute of the ConfigManager instance.
        """
        return self.__log_level

    def get_app_version(self):
        """
        Returns the app version attribute of the ConfigManager instance.
        """
        return self.__version

    def get_app_name(self):
        """
        Returns the app name attribute of the ConfigManager instance.
        """
        return self.__service_name
    
    def get_environment(self):
        """
        Returns the environment attribute of the ConfigManager instance.
        """
        return self.__env

    def get_metrics_port(self):
        """
        Returns the metrics port attribute of the ConfigManager instance.
        """
        return self.__metrics_port

    def get_detection_config_file_path(self):
        """
        Returns the detection config file path attribute of the ConfigManager instance.
        """
        return self.__detection_config_file_path
    
    def get_segmentation_config_file_path(self):
        """
        Returns the segmentation config file path attribute of the ConfigManager instance.
        """
        return self.__segmentation_config_file_path
